language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
  - $TRAVIS_BUILD_DIR/testng/.allure
services:
  - docker
before_script:
  - echo "Starting build"
  - docker run --rm -d --name chrome -p 4444:4444 selenoid/chrome:70.0
  #- docker run --rm -d selenoid/cm:latest-release --browsers chrome --last-versions 1 --args "-limit 2"
script:
  - cd testng
  - mvn test allure:report
after_script:
  - echo "Script finished"
  - ls -l $TRAVIS_BUILD_DIR/testng/target/site/allure-maven-plugin
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - ls -l $TRAVIS_BUILD_DIR/testng/target
after_failure:
  - echo "Build was failed"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: $TRAVIS_BUILD_DIR/testng/target/site/allure-maven-plugin
  repo: simple-elf/simple-elf.github.io
  target-branch: master