version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: docker:17.05.0-ce-git
        command: >
          docker run --rm
          -v /var/run/docker.sock:/var/run/docker.sock
          -v ${HOME}:/root
          -e OVERRIDE_HOME=${HOME}
          aerokube/cm:latest-release selenoid start
          --browsers chrome
          --last-versions 1
          --vnc
          --args "-limit 2"
    working_directory: ~/repo/testng
    steps:
      #- setup_remote_docker
      #- run:
      #    name: Run Selenoid CM
      #    command: >
      #      docker run --rm
      #      -v /var/run/docker.sock:/var/run/docker.sock
      #      -v ${HOME}:/root
      #      -e OVERRIDE_HOME=${HOME}
      #      aerokube/cm:latest-release selenoid start
      #      --browsers chrome
      #      --last-versions 1
      #      --vnc
      #      --args "-limit 2"
      - checkout:
          path: ~/repo

      - restore_cache:
          key: selenoid-video-allure-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline

      - run:
          name: Autotests
          command: mvn test
      - run:
          name: Allure
          command: mvn allure:report

      - save_cache:
          paths:
            - ~/.m2
          key: selenoid-video-allure-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/site/allure-maven-plugin

      #- run:
      #    name: Selenoid stop
      #    command: |
      #      docker stop selenoid
      #      docker rm selenoid