version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo/testng

    steps:
      - setup_remote_docker:
          version: 17.05.0-ce

      - checkout:
          path: ~/repo
      - run:
          name: Run Selenoid CM
          command: >
            docker run --rm
            -v ${HOME}:/root
            -e OVERRIDE_HOME=${HOME}
            aerokube/cm:latest-release selenoid configure
            --browsers chrome
            --last-versions 1
            --vnc
      - run:
          name: Run Selenoid
          command: >
            docker run --rm -d
            --name selenoid
            -p 4444:4444
            -v /var/run/docker.sock:/var/run/docker.sock
            -v `pwd`/config/:/etc/selenoid/:ro
            aerokube/selenoid:latest-release
            -limit 2

      - run:
          name: Check Selenoid
          command: curl http://127.0.0.1:4444/status

      - restore_cache:
          key: selenoid-video-allure-{{ checksum "pom.xml" }}
      - run:
          name: Resolve Maven dependencies
          command: mvn dependency:go-offline compile compiler:testCompile

      #- run:
      #    name: Autotests
      #    command: mvn test
      #- run:
      #    name: Allure Report
      #    command: mvn allure:report

      - save_cache:
          paths:
            - ~/.m2
            - .allure
          key: selenoid-video-allure-{{ checksum "pom.xml" }}
          when: always

      #- store_test_results:
      #    path: target/surefire-reports
      #- store_artifacts:
      #    path: target/surefire-reports
      #- store_artifacts:
      #    path: target/allure-results
      - store_artifacts:
          path: target/site/allure-maven-plugin
          destination: allure-report

      - run:
          name: Selenoid stop
          command: docker stop selenoid